// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5mWTLohSHjG_kzKmkP9REjFI2zOJwms',
    appId: '1:4719334423:android:f347a53bc424a4d7b43852',
    messagingSenderId: '4719334423',
    projectId: 'e-comm-app-project',
    storageBucket: 'e-comm-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFeU7mbTbeRn0dcUuUhHanhGhQJYwKok0',
    appId: '1:4719334423:ios:15d50b7fa3712007b43852',
    messagingSenderId: '4719334423',
    projectId: 'e-comm-app-project',
    storageBucket: 'e-comm-app-project.firebasestorage.app',
    iosBundleId: 'com.kazungudev.eComm',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTvF9p6w19iWRmpiVffwxUZGr_3INkg8',
    appId: '1:4719334423:web:19f738b1d89c25d8b43852',
    messagingSenderId: '4719334423',
    projectId: 'e-comm-app-project',
    authDomain: 'e-comm-app-project.firebaseapp.com',
    storageBucket: 'e-comm-app-project.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFeU7mbTbeRn0dcUuUhHanhGhQJYwKok0',
    appId: '1:4719334423:ios:15d50b7fa3712007b43852',
    messagingSenderId: '4719334423',
    projectId: 'e-comm-app-project',
    storageBucket: 'e-comm-app-project.firebasestorage.app',
    iosBundleId: 'com.kazungudev.eComm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkTvF9p6w19iWRmpiVffwxUZGr_3INkg8',
    appId: '1:4719334423:web:1ec5468d69abf43db43852',
    messagingSenderId: '4719334423',
    projectId: 'e-comm-app-project',
    authDomain: 'e-comm-app-project.firebaseapp.com',
    storageBucket: 'e-comm-app-project.firebasestorage.app',
  );

}